# Generated by Django 5.2.1 on 2025-05-23 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoCiudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('autor', models.CharField(max_length=255)),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now)),
                ('archivo_pdf', models.FileField(upload_to='documentos/pdf/')),
                ('categorias', models.ManyToManyField(related_name='documentos', to='ecos_ciudadania.categoria')),
            ],
        ),
    ]
