# Generated by Django 5.1.7 on 2025-05-24 00:00

import django.core.validators
import ecos_ciudadania.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecos_ciudadania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentociudadano',
            name='correo',
            field=models.EmailField(default='prueba@gmail.com', help_text='Correo de contacto', max_length=255, validators=[django.core.validators.EmailValidator(message='Debe ser un correo electrónico válido')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentociudadano',
            name='telefono',
            field=models.CharField(default='7711234567', help_text='Número de teléfono a 10 dígitos', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Debe ingresar un número de 10 dígitos')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentociudadano',
            name='archivo_pdf',
            field=models.FileField(upload_to='documentos/pdf/', validators=[ecos_ciudadania.models.validar_pdf]),
        ),
    ]
