# Generated by Django 5.1.7 on 2025-04-09 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NivelacionTierra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('folio', models.CharField(blank=True, max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=18)),
                ('cuenta_conagua', models.CharField(max_length=100)),
                ('domicilio', models.TextField()),
                ('identificacion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('municipio', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('distrito_riego', models.CharField(max_length=100)),
                ('modulo_riego', models.CharField(max_length=100)),
                ('superficie_parcela', models.FloatField(help_text='Hectáreas')),
                ('tiempo_promedio_riego', models.FloatField(help_text='Horas')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('grado_pendiente', models.CharField(max_length=100)),
                ('pedregosidad', models.CharField(max_length=100)),
                ('profundidad_suelo', models.CharField(max_length=100)),
                ('tamano_canaleta', models.FloatField(help_text='Tamaño de canaleta (cm)')),
                ('tipo_revestimiento', models.CharField(max_length=100)),
                ('gasto_canales', models.CharField(max_length=100)),
                ('distancia_canaleta', models.FloatField(help_text='Distancia a canaleta (m)')),
                ('tipo_seccion', models.CharField(max_length=100)),
                ('ha_nivelado', models.CharField(max_length=10)),
                ('anio_nivelacion', models.CharField(blank=True, max_length=10, null=True)),
                ('problemas_drenaje', models.CharField(max_length=10)),
                ('cultivos_dominantes', models.CharField(max_length=100)),
                ('cultivo_actual', models.CharField(max_length=100)),
                ('perene_roturacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_libre_parcela', models.CharField(blank=True, max_length=100, null=True)),
                ('acreditacion_propiedad', models.CharField(max_length=10)),
                ('documento_presentado', models.CharField(max_length=100)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='archivos_pdfs/')),
                ('curso_sader', models.CharField(max_length=10)),
                ('cuando_toma_sader', models.CharField(blank=True, max_length=100, null=True)),
                ('firma_digital', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='nivelacion_pdfs/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('nivelacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archivo', to='formulario.nivelaciontierra')),
            ],
        ),
    ]
