# Generated by Django 5.1.7 on 2025-04-11 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_nivelaciontierra_distancia_canaleta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelaciontierra',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
