# Generated by Django 5.1.7 on 2025-04-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_alter_nivelaciontierra_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivopdf',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='archivopdf',
            name='fecha_subida',
        ),
        migrations.AddField(
            model_name='archivopdf',
            name='acreditacion_propiedad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archivopdf',
            name='area_atencion_prioritaria',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='archivopdf',
            name='constancia_curso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='archivopdf',
            name='convenio_colaboracion_pnh',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='archivopdf',
            name='firma_digital',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivopdf',
            name='nivel_pedregosidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archivopdf',
            name='nombre_revisor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='archivopdf',
            name='pendiente_promedio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archivopdf',
            name='profundidad_suelo_pedregosidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archivopdf',
            name='tipo_suelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='archivopdf',
            name='volumen_agua_anual',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
