# Generated by Django 5.1.7 on 2025-04-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_remove_archivopdf_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivopdf',
            name='nivelacion',
            field=models.OneToOneField(db_column='nivelacion', on_delete=django.db.models.deletion.CASCADE, related_name='archivo', to='formulario.nivelaciontierra'),
        ),
    ]
