# Generated by Django 5.1.7 on 2025-04-15 23:03

import formulario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_alter_archivopdf_nivelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelaciontierra',
            name='constancia_pdf',
            field=models.FileField(blank=True, null=True, upload_to=formulario.models.constancia_pdf_path),
        ),
        migrations.AlterField(
            model_name='nivelaciontierra',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to=formulario.models.archivo_pdf_path),
        ),
    ]
