# Generated by Django 5.1.7 on 2025-04-21 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_nivelaciontierra_constancia_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivopdf',
            name='nivelacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archivo', to='formulario.nivelaciontierra'),
        ),
    ]
