# Generated by Django 5.1.7 on 2025-04-24 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_alter_archivopdf_nivelacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelaciontierra',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este formulario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nivelaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
